### PR TITLE
Fix a crash from attempted to read past the end of input when given incomplete input data.

### LINKED ISSUE #199: JSONFromString() does crash on certain inputs.
**Steps to reproduce**

Run JSONFromString() with the following Swift strings as input:
    
    " "
    "[0,"
    "{\"\":"

**Expected behavior**

Since these strings are invalid JSON according to [RFC 7159](https://tools.ietf.org/html/rfc7159), JSONFromString() should throw an error.

**Actual behavior**

JSONFromString() does crash.

### PR DESCRIPTION
**Pull request by jgallagher**
Closes #199.

### CODE REVIEW

**Comment by jeremy-w** [comment]
:+1: LGTM

File: Tests/JSONParserTests.swift [hunk 1]
```diff
@@ -153,6 +153,19 @@ class JSONParserTests: XCTestCase {
         XCTAssertEqual(value, JSON.String(expect))
     }
 
+    func testThatParserFailsWhenIncompleteDataIsPresent() {
+        for s in [" ", "[0,", "{\"\":"] {
+            do {
+                let value = try JSONFromString(" ")
```
Comment (xaxis-kenan) [inline Tests/JSONParserTests.swift]: Erm shouldn't this be `JSONFromString(s)` ?
